export const componentTokenMap = {
  Button: {
    'primary bg': '--ds-color-action-primary-default',
    'primary bg hover': '--ds-color-action-primary-hover',
    'primary bg active': '--ds-color-action-primary-active',
    'secondary bg': '--ds-color-action-secondary-default',
    'accent bg': '--ds-color-action-accent-default',
    'text on action (primary)': '--ds-color-text-on-action-primary',
    'text on action (secondary)': '--ds-color-text-on-action-secondary',
    'text on action (accent)': '--ds-color-text-on-action-accent',
    'ghost text': '--ds-color-text-primary',
    'subtle bg': '--ds-color-bg-muted',
    'focus ring': '--ds-color-border-focus',
    shadow: '--ds-shadow-sm',
  },
  Input: {
    bg: '--ds-color-bg-surface',
    border: '--ds-color-border-default',
    'border hover': '--ds-color-border-focus',
    'border focus': '--ds-color-border-focus',
    text: '--ds-color-text-primary',
    placeholder: '--ds-color-text-muted',
    'error border': '--sys-color-error',
    'error text': '--sys-color-error',
  },
  Card: {
    bg: '--ds-color-bg-surface',
    border: '--ds-color-border-subtle',
    shadow: '--ds-shadow-sm',
  },
  Badge: {
    'subtle bg': '--ds-color-bg-muted',
    'subtle text': '--ds-color-text-primary',
    'primary bg': '--ds-color-action-primary-default',
    'primary text': '--ds-color-text-on-action-primary',
    'secondary bg': '--ds-color-action-secondary-default',
    'secondary text': '--ds-color-text-on-action-secondary',
    'accent bg': '--ds-color-action-accent-default',
    'accent text': '--ds-color-text-on-action-accent',
    'outline color': '--ds-color-action-primary-default',
  },
  Avatar: {
    'primary bg': '--ds-color-action-primary-default',
    'primary initials text': '--ds-color-text-on-action-primary',
    'secondary bg': '--ds-color-action-secondary-default',
    'secondary initials text': '--ds-color-text-on-action-secondary',
    'accent bg': '--ds-color-action-accent-default',
    'accent initials text': '--ds-color-text-on-action-accent',
  },
  Select: {
    'trigger bg': '--ds-color-bg-surface',
    'trigger border': '--ds-color-border-default',
    'trigger text': '--ds-color-text-primary',
    placeholder: '--ds-color-text-muted',
    'focus ring': '--ds-color-action-primary-default',
    'dropdown bg': '--ds-color-bg-elevated',
    'dropdown border': '--ds-color-border-default',
    'dropdown shadow': '--ds-shadow-lg',
    'option text': '--ds-color-text-primary',
    'option hover bg': '--ds-color-bg-muted',
    'selected bg': '--ds-color-action-primary-default',
    'selected text': '--ds-color-text-on-action-primary',
  },
} as const;

export type ComponentTokenMap = typeof componentTokenMap;
